language: node_js
node_js:
  - "11"
install:
  - npm install
script:
  - npm test
notifications:
  slack: omindbrand:HEzxTXkEVus7BOIX5xndikqD
  notifications:
  slack:
    rooms:
      - omindbrand:HEzxTXkEVus7BOIX5xndikqD
    on_success: change # default: always
    on_failure: always # default: always