paths:
  /public/projects/{page}/{limit}:
    get:
      tags:
        - projects
      summary: Get all public projects.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
      parameters:
        - name: page
          in: path
          schema:
            type: integer
        - name: limit
          in: path
          schema:
            type: integer
  /public/projects/{slug}:
    get:
      tags:
        - projects
      summary: Get one public project by slug.
      parameters:
        - name: slug
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
  /projects/{projectId}/videos:
    post:
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
      tags:
        - projects
      summary: Add video.
      requestBody:
        $ref: '#/components/requestBodies/ProjectVideo'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectVideo'
      security:
        - bearerAuth: []
  /projects/{projectId}/videos/{videoId}:
    delete:
      tags:
        - projects
      summary: Delete video.
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
        - name: videoId
          in: path
          schema:
            type: string
      responses:
        '204':
          description: Video deleted successfully
        '400':
          description: Missing id parameter
      security:
        - bearerAuth: []
    patch:
      tags:
        - projects
      summary: Update video
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
        - name: videoId
          in: path
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/ProjectVideo'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectVideo'
        '400':
          description: Missing id parameter
        '404':
          description: Video not found
      security:
        - bearerAuth: []
  /projects/{projectId}/images:
    post:
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
      tags:
        - projects
      summary: Add image.
      requestBody:
        $ref: '#/components/requestBodies/ProjectImage'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectImage'
      security:
        - bearerAuth: []
  /projects/{projectId}/images/{imageId}:
    delete:
      tags:
        - projects
      summary: Delete image.
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
        - name: imageId
          in: path
          schema:
            type: string
      responses:
        '204':
          description: Image deleted successfully
        '400':
          description: Missing id parameter
      security:
        - bearerAuth: []
    patch:
      tags:
        - projects
      summary: Update image
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
        - name: imageId
          in: path
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/ProjectImage'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectImage'
        '400':
          description: Missing id parameter
        '404':
          description: Image not found
      security:
        - bearerAuth: []
  /projects/{page}/{limit}:
    get:
      tags:
        - projects
      summary: Get all projects.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        '403':
          description: Access denied. Insufficient permission.
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: path
          schema:
            type: integer
        - name: limit
          in: path
          schema:
            type: integer
  /projects:
    post:
      tags:
        - projects
      summary: Create project.
      requestBody:
        $ref: '#/components/requestBodies/Project'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Email already exists
      security:
        - bearerAuth: []
  /projects/{id}:
    delete:
      tags:
        - projects
      summary: Delete project.
      parameters:
        - name: id
          in: path
          schema:
            type: string
      responses:
        '204':
          description: Project deleted successfully
        '400':
          description: Missing id parameter
        '403':
          description: Can not delete Admin Project
        '404':
          description: Clint not found
      security:
        - bearerAuth: []
    get:
      tags:
        - projects
      summary: Get one project by id.
      parameters:
        - name: id
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Missing id parameter
        '404':
          description: Project not found
      security:
        - bearerAuth: []
    patch:
      tags:
        - projects
      summary: Update one project
      parameters:
        - name: id
          in: path
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/Project'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Missing id parameter
        '404':
          description: Project not found
      security:
        - bearerAuth: []
components:
  schemas:
    ProjectImage:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        main:
          type: boolean
        coverPage:
          type: boolean
        published:
          type: boolean
        path:
          type: string
    ProjectVideo:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        source:
          type: string
        url:
          type: string
        published:
          type: boolean
    Project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        description:
          type: string
        metaDescription:
          type: string
        startedDate:
          type: string
        finishedDate:
          type: string
        published:
          type: string
        status:
          type: string
        tags:
          type: array
          items:
            type: string
        client:
          type: object
        images:
          type: array
        #employee:
        # type: object
  requestBodies:
    ProjectImage:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              title:
                type: string
              main:
                type: boolean
              coverPage:
                type: boolean
              published:
                type: boolean
              imageFile:
                type: string
                format: binary
    ProjectVideo:
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            type: object
            properties:
              title:
                type: string
              url:
                type: string
              source:
                type: string
              published:
                type: boolean
    Project:
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              metaDescription:
                type: string
              startedDate:
                type: string
                format: date
              finishedDate:
                type: string
                format: date
              published:
                type: boolean
                default: false
              status:
                type: string
              #employee:
              #type: string
              #pmo:
              # type: string
              client:
                type: string
              tags:
                type: array
                items:
                  type: string
